### PR TITLE
[current.php] add _multi.zip

### PR DESCRIPTION
**Pull request by m4dhouse**
Work on the new change

### CODE REVIEW

**Comment by Huevos** [comment]
You need to add `_nand.zip$` see here: https://github.com/oe-alliance/oe-alliance-core/blob/5.0/meta-brands/meta-airdigital/conf/machine/include/zgemma-hisil-3716mv430.inc#L59

And it needs to avoid `_recovery_usb.zip` see here: https://github.com/oe-alliance/oe-alliance-core/commit/5e811e883c17520bb2fc3509edcf255f4ced2b58#diff-aa20d436c9464f87de664b6dd08d062d01125f777ed4d135a15c328e9af8711bR47

For example: `if (is_file("$Path/$file") && preg_match("/$Filter/i", $file) && strpos($file, "recovery") === false) {`

**Comment by m4dhouse** [comment]
Zgemma, Multibox the url doesn't work, example:
https://images.mynonpublic.com/openatv/7.0/current.php?open=zgemmah9sse

**Comment by Huevos** [comment]
Yes, it didn't work but needs fixing properly as suggested above. OpenViX version works fine.

http://www.openvix.co.uk/openvix-builds/current.php?open=zgemmah9sse

**Comment by Huevos** [comment]
I've updated it now, here: https://github.com/oe-alliance/bootmenu/commit/4111292f1d7e04867f44902daac578c0e796978c
and here: https://github.com/oe-alliance/bootmenu/commit/0212c579f89116ab36698d5179f5d65a192b9c95

Obviously each team would need to update there own script on their download server.

Thanks for your help.

**Pull request closed without merging**
