### PR TITLE
Add OpenPLi to the bootmenu of the octagon sfx6008

### PR DESCRIPTION
**Pull request by WanWizard**

### CODE REVIEW

**Comment by atvcaptain** [comment]
not working the link to the image

**Comment by Huevos** [comment]
Works for me. Retrieves: openpli-develop-sfx6008-20221008_multiboot.zip

**Comment by atvcaptain** [comment]
link now working

**Comment by WanWizard** [comment]
Our downloads are behind a CDN, it takes a while before a 404 in the cache is cleared.

**Pull request merged**
