### PR TITLE
Add OV once again

### PR DESCRIPTION
**Pull request by persianpros**

### CODE REVIEW

**Comment by Huevos** [comment]
https://github.com/OpenVisionE2/bootmenu/commit/f5755aea8ebfdc4c4858d3ae91d95718532feea9

That commit is spreading false information that is poisoning the climate in the e2 community. Please remove it and clear the git history.

**Comment by persianpros** [comment]
I reverted the commits days ago after OpenSPA decided to go Open again and publish their e2 code: https://github.com/OpenSPA/dvbapp2/commit/af365d1410ddd18d9a4b69ca9fa7dabc1fd5000c

So there was no false information and exactly after my commits we saw OpenSPA started to publish their sources on their git and OE-A like https://github.com/oe-alliance/oe-alliance-core/commit/12be3fe9ce0595b2f9d0bcb936c54cd1cdb29c7c

BTW I didn't see any rule on https://github.com/oe-alliance/bootmenu/blob/master/README.md (rules section) mentioning you care about other git commits on other organizations which is weird.

**Comment by atvcaptain** [comment]
You play the GPL guardian, but also with you everything is hidden, I'm not talking about E2, because you also use my FTP server to download the driver files and certainly many other things that come from us, you should be so fair and then also make everything public where our work is in it, only then we can take you seriously.
Any cooperation and help is also welcome from you, because I think it's good if more people help, but there should be trust, and sharing means not only taking.

**Comment by persianpros** [comment]
I suggest you add some new rules to your rules section then as you wrote "The images must be freely available for the user to download." which we have/had always so what's the real problem here? You don't respect your own decisions or that README.md file is not real?

I sent this PR by request, we have our own repo at https://github.com/OpenVisionE2/bootmenu

We cherry-pick from ATV's e2 just like ATV takes from us, about downloading drivers we could setup a new URL and put all the drivers on it. Not big deal to have another mirror just let me know.

Check your repos on OE-A and you'll find me as "contributor" in most of them but you won't get new PRs on OE-A from me because of how you treat devs exactly like this PR. You won't accept a correct PR not because of a problem in the code but because you don't like the person who sent it. So mature.

Some of you have personal problems with me (I'm sure of it although I don't have any personal problems with you) and reflect it on other things, it's your loss not mine as I'm up for help/contribute always and you refuse to get it.

It doesn't matter what I send or what I do, you don't just like it because you don't like me.

Here you don't even know what reason to find to reject my PR and you're just making excuses to not accept it.

Fine with me, wish you the best.

**Comment by atvcaptain** [comment]
I guess you forget that you are spreading false information, we had rebuilt the rules to include close source teams, so OV too, then you come up with deliberate claims and insult me and the openSPA team, that your pull will be held back due to your childish behavior should be obvious to you.

You should rethink your way of working and not always beat everyone over the head

you can help or leave it alone but refrain from making false claims because i have a problem with that.

if others are to respeck you, then you should not be a hypocrite. beg for source but hide everything yourself.

**Comment by persianpros** [comment]
I didn't spread any false information, exactly after my commits OpenSPA decided to go open again right? Do I need to show the time of the commits or is that enough?

Also ATV is not buildable for dreamone and dreamtwo so I write corretly about those. OpenATV is OpenATV for all except dreamone and dreamtwo which is ATV. I reverted the name changes days ago.

Show me where did I insult you? Seems you're picking things up for yourself to call it an insult to make an excuse to do something else.

Obviously I can see the "childish behavior", reject PRs because you have personal problems with the author this so "mature".

**Pull request closed without merging**
